version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile.dev
    container_name: backend-dev
    ports:
      - '3000:3000'
    volumes:
      - ./apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - apps/backend/.env
    depends_on:
      - db

  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile.dev
    container_name: frontend-dev
    ports:
      - '5173:5173' # Expose Vite development server port
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    volumes:
      - ./apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  db:
    image: postgres:16-alpine
    container_name: db-dev
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5433:5432' # Expose PostgreSQL port to host machine
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
