FROM rust:1.80-bullseye

WORKDIR /usr/src/app

RUN cargo install cargo-watch
# Copy the Cargo.toml and Cargo.lock files from the workspace root
COPY Cargo.toml Cargo.lock ./

# Copy the .env file
COPY apps/starship-rs/.env .

# Copy the source code
COPY apps/starship-rs/src ./src

# Set the command to run the application with live reloading
CMD ["cargo", "watch", "-x", "run"]