FROM rust:1.80-bullseye

WORKDIR /usr/src/app

# Copy the Cargo.toml and Cargo.lock files from the workspace root
COPY Cargo.toml Cargo.lock ./

# Copy the .env file
COPY apps/starship-rs/.env .

# Copy the source code
COPY apps/starship-rs/src ./src

# Build the executable
RUN cargo build --release

# Set the binary as the entrypoint
ENTRYPOINT ["./target/release/starship-rs"]

# Default command to show help
CMD ["--help"]