# Use the official Rust image as the base image
FROM rust:1.80-bullseye

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the entire workspace
COPY . .

# Change to the starship-rs directory
WORKDIR /usr/src/app/apps/starship-rs

# Build the starship-rs application
RUN cargo build --release

# Change back to the main workspace directory
WORKDIR /usr/src/app

# Wait for commands
CMD ["tail", "-f", "/dev/null"]