//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use super::sea_orm_active_enums::ProcessStatus;
use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "processed_transactions")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub transaction_id: String,
    pub program_id: String,
    #[sea_orm(column_type = "Text")]
    pub transaction_type: String,
    pub starship_version: String,
    pub external_version: String,
    pub process_status: ProcessStatus,
    pub retries: i16,
    pub processed_at: Option<DateTime>,
    pub block_time: Option<i64>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
