//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.1

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "tickers")]
pub struct Model {
    pub external_id: String,
    pub creator: String,
    pub featured: bool,
    pub name: String,
    pub symbol: String,
    pub image: String,
    #[sea_orm(column_type = "Text")]
    pub curve_type: String,
    pub price: i32,
    pub volume: i32,
    pub market_cap: i32,
    pub tvl: i32,
    pub completion_percentage: i32,
    pub creation_date: DateTime,
    pub indexed_date: DateTime,
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: Uuid,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
